// src/components/BasicAdmin.vue
<template>
<v-app id="app">

  <vxg-basic-head
    :spec="spec.parts.head"
    :logo="logo"
    @action="action('BasicHead', $event)"
    />

  <vxg-basic-side
    v-if="showSide"
    :spec="spec.parts.side"
    :logo="logo"
    @action="action('BasicSide', $event)"
    />

  <vxg-basic-main
    :spec="spec.parts.main"
    />

  
  <vxg-basic-foot
    :spec="spec.parts.foot"
    />

</v-app>
</template>

<style lang="scss"></style>

<script>
export default {
  props: ['logo'],
  data () {
    return {
      spec: this.$model.main.app.web
    }
  },

  created () {
  },

  computed: {
    showSide() {
      return this.$store.state.vxg.cmp.BasicSide.show
    }
  },

  methods: {
    action(part, ev) {
      this.$emit('action', {part,event:ev})
    }
  }
}
</script>

// src/lib/BasicAdmin.tsx

import React from 'react'

import BasicHead from './BasicHead'
import BasicSide from './BasicSide'
import BasicMain from './BasicMain'
import BasicFoot from './BasicFoot'


function BasicAdmin(props: any) {
  const {
    vxg,
    ctx,
    spec
  } = props
  const model = ctx().model

  const { frame } = spec

  // spec schema definition with Gubu
  const shape = Gubu({
    frame: String
  })

  // spec schema validation with Gubu
  shape(spec)

  const frameModel = model.app.web.frame[frame]

  const headSpec: any = {
    head: frameModel.part.head,
    view: frameModel.view,
  }

  const sideSpec: any = {
    side: frameModel.part.side,
    view: frameModel.view,
  }

  const mainSpec: any = {
    main: frameModel.part.main,
    view: frameModel.view,
  }

  const footSpec: any = {
    foot: frameModel.part.foot,
    view: frameModel.view,
  }

  return (
    <div>
      <BasicHead vxg={vxg} ctx={ctx} spec={headSpec} />
      <BasicSide vxg={vxg} ctx={ctx} spec={sideSpec} />
      <BasicMain vxg={vxg} ctx={ctx} spec={mainSpec} />
      <BasicFoot vxg={vxg} ctx={ctx} spec={footSpec} />
    </div>
  )
}

export default BasicAdmin
